### ISSUE TITLE
Giving a None-Type object error

### ISSUE THREAD

**Issue by SiddhantMeshram** [nutztherookie/django-informix#1]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Library/Python/2.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Library/Python/2.7/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Library/Python/2.7/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 212, in __getitem__
    conn = backend.DatabaseWrapper(db, alias)
  File "/Library/Python/2.7/site-packages/django_informix-1.5-py2.7.egg/django_informix/base.py", line 74, in __init__
  File "/Library/Python/2.7/site-packages/django/db/backends/base/base.py", line 96, in __init__
    self.client = self.client_class(self)
TypeError: Error when calling the metaclass bases
    'NoneType' object is not callable

**Comment by andreasnuesslein** [comment]
Hey @SiddhantMeshram ,
thanks for your report. I'm assuming you're using a newer Django version? I haven't maintained this in a while.
Which version is it?

Cheers

**Comment by gummadidala** [comment]
I am also getting the same error. I am using Django 1.11.15 version.

**Comment by andreasnuesslein** [comment]
Hey folks,

I'm really not maintaining this anymore. :(
Can you provide PRs? I will gladly pull them
